const layouts = {
  // ======================= HOME SCREEN =======================
  HOME_HEADER_TOP: 5,
  TARGET_WORD_TOP: 455,
  HOME_BUTTON_TOP: 470,
  HOME_BUTTON_GAP: 30,
  HOME_BUTTON_PADDING_HORIZONTAL: 15,
  HOME_BUTTON_PADDING_VERTICAL: 5,
  HOME_BUTTON_BORDER_RADIUS: 20,
  HOME_BUTTON_BORDER_WIDTH: 2,

  // ======================= GAME GRID =======================
  GAME_GRID_TOP: 249,
  GAME_GRID_SIZE: 380,
  GAME_GRID_BORDER_RADIUS: 13,
  GAME_GRID_PADDING: 7,
  GAME_GRID_CELL_DIVISOR: 4.6,
  GAME_GRID_CELL_MARGIN: 4,
  GAME_GRID_CELL_BORDER_WIDTH: 3,
  TILE_SIZE: 380 / 4.6,
  TILE_MARGIN_TOP: 4,
  TILE_MARGIN_BOTTOM: 4,
  TILE_MARGIN_LEFT: 4,
  TILE_MARGIN_RIGHT: 4,
  TILE_BORDER_WIDTH: 3,

  // ======================= GAME BOARD =======================
  GAME_BOARD_TOP: 25,
  GAME_BOARD_HEIGHT: 83,
  GAME_BOARD_BORDER_WIDTH: 2,
  GAME_BOARD_BORDER_RADIUS: 27,
  GAME_BOARD_GAP: 35,
  GAME_BOARD_PADDING_HORIZONTAL: 20,
  GAME_BOARD_COUNT_HEIGHT: 40,
  SCORE_BOARD_WIDTH: 160,
  POPS_BOARD_WIDTH: 120,

  // ======================= MENU SCREEN =======================
  SOUND_BUTTON_TOP: 135,
  MENU_BUTTON_TOP: 215,
  MENU_BUTTON_MARGIN_TOP: 25,
  MENU_BUTTON_BORDER_RADIUS: 33,
  MENU_BUTTON_BORDER_WIDTH: 2,
  MENU_BUTTON_PADDING_HORIZONTAL: 25,
  MENU_BUTTON_PADDING_VERTICAL: 10,
  RESUME_BUTTON_MARGIN_BOTTOM: 20,
  RESUME_BUTTON_SCALE: 1.18,
  RATE_BUTTON_SCALE: 1.1,

  // ======================= WORD PACK SCREEN =======================
  WORD_PACK_BUTTON_WIDTH: 310,
  WORD_PACK_BUTTON_HEIGHT: 80,
  WORD_PACK_BUTTON_BORDER_RADIUS: 30,
  WORD_PACK_BUTTON_BORDER_WIDTH: 2,
  WORD_PACK_BUTTON_TOP: 10,
  WORD_PACK_BUTTON_MARGIN_TOP: 23,
  WORD_PACK_ICON_SIZE: 80,
  WORD_PACK_ICON_MARGIN_LEFT: 20,
  WORD_PACK_TEXT_MARGIN_LEFT: 9,
  WORD_PACK_TEXT_MARGIN_TOP: -10,
  WORD_PACK_TITLE_WIDTH: 400,
  WORD_PACK_TITLE_HEIGHT: 56,
  WORD_PACK_TITLE_MARGIN_BOTTOM: 18,
  WORD_PACK_SUBTITLE_WIDTH: 340,
  WORD_PACK_SUBTITLE_MARGIN_TOP: 4,
  NATURE_ICON_TOP: -5,
  FOOD_ICON_TOP: -5,
  ANIMALS_ICON_SCALE: 1.05,

  // ======================= GAME LAB SCREEN =======================
  GAME_LAB_HEADER_TOP: 155,
  GAME_LAB_BUTTON_WIDTH: 320,
  GAME_LAB_BUTTON_HEIGHT: 87,
  GAME_LAB_BUTTON_BORDER_RADIUS: 30,
  GAME_LAB_BUTTON_BORDER_WIDTH: 2,
  GAME_LAB_BUTTON_MARGIN_TOP: 26,
  GAME_LAB_BUTTON_TOP: 160,
  GAME_LAB_ICON_SIZE: 78,
  GAME_LAB_ICON_MARGIN_LEFT: 15,
  GAME_LAB_TEXT_MARGIN_LEFT: 2,
  GAME_LAB_TEXT_MARGIN_TOP: -2,
  GAME_LAB_TITLE_MARGIN_BOTTOM: 15,
  GAME_LAB_SUBTITLE_WIDTH: 340,
  GAME_LAB_SUBTITLE_MARGIN_TOP: 2,

  // ======================= GAME LAB ADJUSTMENTS =======================
  DIFFICULTY_MARGIN_LEFT: -3,
  DIFFICULTY_ICON_SCALE: 0.94,
  EDIT_TILE_MARGIN_TOP: 2,
  EDIT_TILE_ICON_SCALE: 0.9,
  JUMP_TILE_ICON_SCALE: 1.08,
  JUMP_TILE_ICON_MARGIN_TOP: 4,
  ERASER_TILE_ICON_SCALE: 0.85,
  ERASER_TILE_ICON_MARGIN_TOP: 5,
  ERASER_TILE_MARGIN_TOP: -10,
  ERASER_TILE_ICON_MARGIN_LEFT: -3,
  QUEST_MODE_MARGIN_LEFT: -3,

  // ======================= DIFFICULTY SCREEN =======================
  DIFFICULTY_BUTTON_WIDTH: 350,
  DIFFICULTY_BUTTON_HEIGHT: 100,
  DIFFICULTY_BUTTON_BORDER_RADIUS: 30,
  DIFFICULTY_BUTTON_BORDER_WIDTH: 5,
  DIFFICULTY_BUTTON_MARGIN_TOP: 25,

  // ======================= ICON SIZES & SPACING =======================
  BACK_ICON_SIZE: 70,
  SOUND_ICON_SIZE: 70,
  RESUME_ICON_SIZE: 50,
  MENU_ICON_MARGIN_RIGHT: 8,

  // ======================= GENERAL LETTER SPACING =======================
  LETTER_SPACING_XS: 0.5,
  LETTER_SPACING_SMALL: 1,
  LETTER_SPACING_MEDIUM: 1.5,
  LETTER_SPACING_LARGE: 2.5,

  // ======================= PACKS =======================
  // Nature Pack
  NATURE_PACK_TITLE_TOP: -3,
  NATURE_PACK_WORD_TOP: -8,
  NATURE_PACK_WORD_MARGIN_BOTTOM: -23,
  NATURE_PACK_LETTER_SPACING: 5,

  // Food Pack
  FOOD_PACK_TITLE_TOP: -7,
  FOOD_PACK_WORD_TOP: -6,
  FOOD_PACK_WORD_MARGIN_BOTTOM: -3,
  FOOD_PACK_LETTER_SPACING: 5,

  // Animals Pack
  ANIMALS_PACK_TITLE_TOP: -10,
  ANIMALS_PACK_WORD_TOP: -15,
  ANIMALS_PACK_WORD_MARGIN_BOTTOM: -20,
  ANIMALS_PACK_LETTER_SPACING: 5,

  // Story Pack
  STORY_PACK_TITLE_TOP: 4,
  STORY_PACK_WORD_TOP: 10,
  STORY_PACK_WORD_MARGIN_BOTTOM: 14,
  STORY_PACK_LETTER_SPACING: -1,
};

export default layouts;
