const layouts = {
  // Home Screen
  HOME_HEADER_TOP: 5,
  HOME_BUTTON_TOP: 475,
  HOME_BUTTON_GAP: 30,
  HOME_BUTTON_PADDING_HORIZONTAL: 15,
  HOME_BUTTON_PADDING_VERTICAL: 5,
  HOME_BUTTON_BORDER_RADIUS: 20,
  HOME_BUTTON_BORDER_WIDTH: 2,

  // Game Board Layout
  GAME_BOARD_TOP: 30,
  GAME_BOARD_HEIGHT: 83,
  GAME_BOARD_BORDER_WIDTH: 2,
  GAME_BOARD_BORDER_RADIUS: 27,
  GAME_BOARD_GAP: 35,
  GAME_BOARD_PADDING_HORIZONTAL: 20,
  GAME_BOARD_COUNT_HEIGHT: 40,
  SCORE_BOARD_WIDTH: 160,
  POPS_BOARD_WIDTH: 120,

  // Target Word
  TARGET_WORD_TOP: 457,
  TARGET_WORD_MARGIN_TOP: 5,

  // Menu Screen
  MENU_BUTTON_TOP: -120,
  MENU_BUTTON_MARGIN_TOP: 25,
  MENU_BUTTON_BORDER_RADIUS: 33,
  MENU_BUTTON_BORDER_WIDTH: 2,
  MENU_BUTTON_PADDING_HORIZONTAL: 25,
  MENU_BUTTON_PADDING_VERTICAL: 10,
  RESUME_BUTTON_MARGIN_BOTTOM: 20,
  RESUME_BUTTON_SCALE: 1.18,
  RATE_BUTTON_SCALE: 1.1,

  // Word Pack Screen
  WORD_PACK_BUTTON_WIDTH: 310,
  WORD_PACK_BUTTON_HEIGHT: 80,
  WORD_PACK_BUTTON_BORDER_RADIUS: 30,
  WORD_PACK_BUTTON_BORDER_WIDTH: 2,
  WORD_PACK_BUTTON_TOP: 20,
  WORD_PACK_BUTTON_MARGIN_TOP: 23,
  WORD_PACK_ICON_SIZE: 80,
  WORD_PACK_ICON_MARGIN_LEFT: 20,
  WORD_PACK_TEXT_MARGIN_LEFT: 9,
  WORD_PACK_TEXT_MARGIN_TOP: -10,
  WORD_PACK_TITLE_WIDTH: 400,
  WORD_PACK_TITLE_HEIGHT: 56,
  WORD_PACK_TITLE_MARGIN_BOTTOM: 18,
  WORD_PACK_SUBTITLE_WIDTH: 340,
  WORD_PACK_SUBTITLE_MARGIN_TOP: 4,
  NATURE_ICON_TOP: -5,
  FOOD_ICON_TOP: -5,
  ANIMALS_ICON_SCALE: 1.05,

  // Game Lab Screen
  GAME_LAB_HEADER_TOP: 115,
  GAME_LAB_BUTTON_WIDTH: 320,
  GAME_LAB_BUTTON_HEIGHT: 83,
  GAME_LAB_BUTTON_BORDER_RADIUS: 30,
  GAME_LAB_BUTTON_BORDER_WIDTH: 2,
  GAME_LAB_BUTTON_MARGIN_TOP: 24,
  GAME_LAB_BUTTON_TOP: 120,
  GAME_LAB_ICON_SIZE: 78,
  GAME_LAB_ICON_MARGIN_LEFT: 21,
  GAME_LAB_TEXT_MARGIN_LEFT: 10,
  GAME_LAB_TEXT_MARGIN_TOP: -5,
  GAME_LAB_TITLE_MARGIN_BOTTOM: 15,
  GAME_LAB_SUBTITLE_WIDTH: 340,
  GAME_LAB_SUBTITLE_MARGIN_TOP: 2,

  // Game Lab Adjustments
  DIFFICULTY_MARGIN_LEFT: -3,
  EDIT_TILE_MARGIN_TOP: 1,
  JUMP_TILE_ICON_SCALE: 1.08,
  ERASER_TILE_ICON_SCALE: 0.88,
  ERASER_TILE_MARGIN_TOP: 0,
  QUEST_MODE_MARGIN_LEFT: -3,

  // Difficulty Buttons
  DIFFICULTY_BUTTON_WIDTH: 350,
  DIFFICULTY_BUTTON_HEIGHT: 100,
  DIFFICULTY_BUTTON_BORDER_RADIUS: 30,
  DIFFICULTY_BUTTON_BORDER_WIDTH: 6,
  DIFFICULTY_BUTTON_MARGIN_TOP: 25,

  // Icon Sizes & Spacing
  BACK_ICON_SIZE: 70,
  SOUND_ICON_SIZE: 70,
  RESUME_ICON_SIZE: 50,
  MENU_ICON_MARGIN_RIGHT: 8,

  // General Letter Spacing
  LETTER_SPACING_XS: 0.5,
  LETTER_SPACING_SMALL: 1,
  LETTER_SPACING_MEDIUM: 1.5,
  LETTER_SPACING_LARGE: 2.5,

  // Target Word Letter Spacing
  NATURE_LETTER_SPACING: 4,
  FOOD_LETTER_SPACING: 10,
  ANIMALS_LETTER_SPACING: 2,
  STORY_LETTER_SPACING: -2,

  // Target Word Margins
  NATURE_TEXT_MARGIN_BOTTOM: -20,
  FOOD_TEXT_MARGIN_BOTTOM: -10,
  ANIMALS_TEXT_MARGIN_TOP: -5,
  ANIMALS_TEXT_MARGIN_BOTTOM: -10,
  STORY_TEXT_MARGIN_TOP: 10,
  STORY_TEXT_MARGIN_BOTTOM: 5,
};

export default layouts;
